// Bundles the MCP App widgets in mcp-app/* into single-file HTML and emits them
// as TS string modules under lib/mcp/app/, so the MCP route can serve them
// without touching the filesystem at runtime (Vercel functions have no
// guaranteed working directory). Runs before `next build`; commit the output.
import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const APPS = [{ name: "book", entry: "mcp-app/book/book.ts", html: "mcp-app/book/book.html", out: "lib/mcp/app/book-html.generated.ts", exportName: "BOOK_APP_HTML" }];

for (const app of APPS) {
  const result = await build({
    entryPoints: [app.entry],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    minify: true,
    legalComments: "none",
    logLevel: "warning",
  });
  const js = result.outputFiles[0].text;
  const html = (await readFile(app.html, "utf8")).replace(
    /<script type="module" src="\.\/[^"]+"><\/script>/,
    () => `<script>${js.replace(/<\/script/gi, "<\\/script")}</script>`,
  );
  // Hosts cache ui:// resources by URI. A content hash in the URI means every
  // change to the widget is a new URI, so no host ever renders a stale card.
  const hash = createHash("sha256").update(html).digest("hex").slice(0, 10);
  const ts = `// GENERATED by scripts/build-mcp-app.mjs from ${app.html} + ${app.entry}. Do not edit.\n` +
    `// Rebuild with: npm run build:mcp-app\n` +
    `export const ${app.exportName}_HASH = ${JSON.stringify(hash)};\n` +
    `export const ${app.exportName} = ${JSON.stringify(html)};\n`;
  await mkdir(path.dirname(app.out), { recursive: true });
  await writeFile(app.out, ts);
  console.log(`${app.out}: ${(html.length / 1024).toFixed(0)} KB (js ${(js.length / 1024).toFixed(0)} KB) hash ${hash}`);
}
