-- Agent skills — the "/" menu's catalogue.
--
-- Sourced from CaseMark's open medical-skills library
-- (github.com/CaseMark/skills, skills/med), filtered to what a behavioral-health
-- practice actually does and mapped onto the agent that owns the work:
-- Friday holds clinical documentation, assessment, care planning and
-- medication; Sal holds coding and revenue cycle; Bev holds credentialing and
-- compliance.
--
-- Rows, not a TypeScript array, because this list grows: adding a skill should
-- be an INSERT, not a deploy. `prompt` is what the composer inserts today —
-- when skills get real dispatch it becomes the instruction the route loads.
--
-- Lives in the PUBLIC/reference database. Nothing here is PHI: these are
-- procedure definitions, not patient data.

CREATE TABLE IF NOT EXISTS agent_skills (
  slug        TEXT PRIMARY KEY,
  agent_id    TEXT NOT NULL,
  group_label TEXT NOT NULL,
  title       TEXT NOT NULL,
  description TEXT NOT NULL,
  prompt      TEXT NOT NULL,
  source      TEXT NOT NULL DEFAULT 'casemark/skills',
  active      BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agent_skills_agent ON agent_skills(agent_id) WHERE active;

COMMENT ON TABLE agent_skills IS 'Catalogue behind the composer''s "/" menu. One row per skill; agent_id scopes which agent offers it.';

INSERT INTO agent_skills (slug, agent_id, group_label, title, description, prompt) VALUES
  ('documenting-psychotherapy-notes', 'friday', 'Documentation', 'Documenting psychotherapy notes', 'Structures psychotherapy documentation meeting billing and clinical requirements. Use when documenting therapy sessions, writing progress notes, or recording psychotherapy interventions.', 'Apply the "Documenting psychotherapy notes" skill. Structures psychotherapy documentation meeting billing and clinical requirements. Use when documenting therapy sessions, writing progress notes, or recording psychotherapy interventions.'),
  ('documenting-mental-status-exams', 'friday', 'Documentation', 'Documenting mental status exams', 'Creates structured MSE documentation covering appearance, behavior, speech, mood, thought, cognition, and insight. Use when documenting mental status, writing MSE sections, or describing psychiatric findings.', 'Apply the "Documenting mental status exams" skill. Creates structured MSE documentation covering appearance, behavior, speech, mood, thought, cognition, and insight. Use when documenting mental status, writing MSE sections, or describing psychiatric findings.'),
  ('abstracting-clinical-documentation', 'friday', 'Documentation', 'Abstracting clinical documentation', 'Extracts codeable diagnoses and procedures from clinical notes with specificity capture. Use when abstracting medical records, identifying codeable conditions, or capturing documentation specificity.', 'Apply the "Abstracting clinical documentation" skill. Extracts codeable diagnoses and procedures from clinical notes with specificity capture. Use when abstracting medical records, identifying codeable conditions, or capturing documentation specificity.'),
  ('documenting-informed-consent', 'friday', 'Documentation', 'Documenting informed consent', 'Structures informed consent documentation with risks, benefits, alternatives, and patient understanding confirmation. Use when obtaining informed consent, documenting consent discussions, or verifying consent completeness.', 'Apply the "Documenting informed consent" skill. Structures informed consent documentation with risks, benefits, alternatives, and patient understanding confirmation. Use when obtaining informed consent, documenting consent discussions, or verifying consent completeness.'),
  ('assessing-suicide-risk', 'friday', 'Assessment', 'Assessing suicide risk', 'Applies Columbia Suicide Severity Rating Scale and structured risk assessment frameworks. Use when assessing suicide risk, documenting safety evaluations, or creating safety plans.', 'Apply the "Assessing suicide risk" skill. Applies Columbia Suicide Severity Rating Scale and structured risk assessment frameworks. Use when assessing suicide risk, documenting safety evaluations, or creating safety plans.'),
  ('managing-depression-screening', 'friday', 'Assessment', 'Managing depression screening', 'Administers and interprets PHQ-9 with severity-based treatment pathways and safety assessment. Use when screening for depression, interpreting PHQ scores, or initiating mental health treatment.', 'Apply the "Managing depression screening" skill. Administers and interprets PHQ-9 with severity-based treatment pathways and safety assessment. Use when screening for depression, interpreting PHQ scores, or initiating mental health treatment.'),
  ('managing-adhd-assessments', 'friday', 'Assessment', 'Managing adhd assessments', 'Structures ADHD evaluation with symptom scales, behavioral observation, and differential diagnosis. Use when evaluating ADHD, administering rating scales, or documenting ADHD assessments.', 'Apply the "Managing adhd assessments" skill. Structures ADHD evaluation with symptom scales, behavioral observation, and differential diagnosis. Use when evaluating ADHD, administering rating scales, or documenting ADHD assessments.'),
  ('conducting-psychiatric-evaluations', 'friday', 'Assessment', 'Conducting psychiatric evaluations', 'Structures comprehensive psychiatric evaluation with MSE, diagnostic formulation, and risk assessment. Use when performing psychiatric assessments, documenting mental status exams, or creating diagnostic formulations.', 'Apply the "Conducting psychiatric evaluations" skill. Structures comprehensive psychiatric evaluation with MSE, diagnostic formulation, and risk assessment. Use when performing psychiatric assessments, documenting mental status exams, or creating diagnostic formulations.'),
  ('conducting-cognitive-assessments', 'friday', 'Assessment', 'Conducting cognitive assessments', 'Administers and interprets cognitive screening tools (MoCA, MMSE, SLUMS) with dementia evaluation. Use when screening for cognitive impairment, administering MoCA/MMSE, or evaluating dementia.', 'Apply the "Conducting cognitive assessments" skill. Administers and interprets cognitive screening tools (MoCA, MMSE, SLUMS) with dementia evaluation. Use when screening for cognitive impairment, administering MoCA/MMSE, or evaluating dementia.'),
  ('managing-substance-use-disorders', 'friday', 'Assessment', 'Managing substance use disorders', 'Structures SUD assessment with ASAM criteria placement, MAT protocols, and recovery planning. Use when assessing substance use, applying ASAM criteria, or managing medication-assisted treatment.', 'Apply the "Managing substance use disorders" skill. Structures SUD assessment with ASAM criteria placement, MAT protocols, and recovery planning. Use when assessing substance use, applying ASAM criteria, or managing medication-assisted treatment.'),
  ('creating-treatment-plans-psychiatric', 'friday', 'Care planning', 'Creating treatment plans psychiatric', 'Structures psychiatric treatment plans with diagnoses, goals, interventions, and measurable outcomes. Use when creating psychiatric treatment plans, setting therapeutic goals, or documenting treatment modalities.', 'Apply the "Creating treatment plans psychiatric" skill. Structures psychiatric treatment plans with diagnoses, goals, interventions, and measurable outcomes. Use when creating psychiatric treatment plans, setting therapeutic goals, or documenting treatment modalities.'),
  ('coordinating-care-transitions', 'friday', 'Care planning', 'Coordinating care transitions', 'Manages post-hospitalization follow-up with medication reconciliation and readmission prevention. Use when following up after discharge, preventing readmissions, or coordinating transitional care.', 'Apply the "Coordinating care transitions" skill. Manages post-hospitalization follow-up with medication reconciliation and readmission prevention. Use when following up after discharge, preventing readmissions, or coordinating transitional care.'),
  ('managing-acute-psychiatric-crises', 'friday', 'Care planning', 'Managing acute psychiatric crises', 'Guides acute agitation management with de-escalation and emergency medication protocols. Use when managing psychiatric crises, treating acute agitation, or implementing emergency interventions.', 'Apply the "Managing acute psychiatric crises" skill. Guides acute agitation management with de-escalation and emergency medication protocols. Use when managing psychiatric crises, treating acute agitation, or implementing emergency interventions.'),
  ('managing-psychiatric-emergencies', 'friday', 'Care planning', 'Managing psychiatric emergencies', 'Guides acute psychiatric assessment including safety evaluation and involuntary hold criteria. Use when evaluating psychiatric emergencies, assessing suicidality, or initiating involuntary holds.', 'Apply the "Managing psychiatric emergencies" skill. Guides acute psychiatric assessment including safety evaluation and involuntary hold criteria. Use when evaluating psychiatric emergencies, assessing suicidality, or initiating involuntary holds.'),
  ('managing-controlled-substances', 'friday', 'Medication', 'Managing controlled substances', 'Tracks controlled substance prescribing with PDMP review, risk assessment, and compliance monitoring. Use when managing controlled substances, reviewing PDMP data, or monitoring opioid prescribing.', 'Apply the "Managing controlled substances" skill. Tracks controlled substance prescribing with PDMP review, risk assessment, and compliance monitoring. Use when managing controlled substances, reviewing PDMP data, or monitoring opioid prescribing.'),
  ('reviewing-medication-safety', 'friday', 'Medication', 'Reviewing medication safety', 'Identifies high-alert medication risks with ISMP guidelines and safety barriers. Use when reviewing high-risk medications, implementing safety checks, or preventing medication errors.', 'Apply the "Reviewing medication safety" skill. Identifies high-alert medication risks with ISMP guidelines and safety barriers. Use when reviewing high-risk medications, implementing safety checks, or preventing medication errors.'),
  ('assessing-drug-interactions', 'friday', 'Medication', 'Assessing drug interactions', 'Identifies clinically significant drug-drug, drug-food, and drug-disease interactions with severity grading and management recommendations. Use when checking drug interactions, evaluating polypharmacy risks, or managing medication combinations.', 'Apply the "Assessing drug interactions" skill. Identifies clinically significant drug-drug, drug-food, and drug-disease interactions with severity grading and management recommendations. Use when checking drug interactions, evaluating polypharmacy risks, or managing medication combinations.'),
  ('coding-behavioral-health-services', 'sal', 'Coding', 'Coding behavioral health services', 'Assigns behavioral health procedure codes with time-based requirements and modifier application. Use when coding therapy sessions, applying psychiatric codes, or documenting behavioral health services.', 'Apply the "Coding behavioral health services" skill. Assigns behavioral health procedure codes with time-based requirements and modifier application. Use when coding therapy sessions, applying psychiatric codes, or documenting behavioral health services.'),
  ('coding-telehealth-services', 'sal', 'Coding', 'Coding telehealth services', 'Assigns telehealth-specific codes with place of service, modifier, and technology requirements. Use when coding virtual visits, applying telehealth modifiers, or documenting telemedicine services.', 'Apply the "Coding telehealth services" skill. Assigns telehealth-specific codes with place of service, modifier, and technology requirements. Use when coding virtual visits, applying telehealth modifiers, or documenting telemedicine services.'),
  ('coding-medical-encounters', 'sal', 'Coding', 'Coding medical encounters', 'Assigns ICD-10-CM diagnosis codes and CPT/HCPCS procedure codes with supporting documentation validation. Use when coding medical visits, selecting diagnosis codes, or assigning procedure codes.', 'Apply the "Coding medical encounters" skill. Assigns ICD-10-CM diagnosis codes and CPT/HCPCS procedure codes with supporting documentation validation. Use when coding medical visits, selecting diagnosis codes, or assigning procedure codes.'),
  ('auditing-coding-accuracy', 'sal', 'Revenue cycle', 'Auditing coding accuracy', 'Reviews coded encounters for accuracy using OIG compliance guidelines and CMS documentation requirements. Use when auditing medical codes, reviewing coding accuracy, or conducting compliance audits.', 'Apply the "Auditing coding accuracy" skill. Reviews coded encounters for accuracy using OIG compliance guidelines and CMS documentation requirements. Use when auditing medical codes, reviewing coding accuracy, or conducting compliance audits.'),
  ('managing-coding-denials', 'sal', 'Revenue cycle', 'Managing coding denials', 'Analyzes claim denials and structures appeal documentation with supporting clinical evidence. Use when appealing denied claims, analyzing denial patterns, or preparing appeal documentation.', 'Apply the "Managing coding denials" skill. Analyzes claim denials and structures appeal documentation with supporting clinical evidence. Use when appealing denied claims, analyzing denial patterns, or preparing appeal documentation.'),
  ('managing-clinical-documentation-improvement', 'sal', 'Revenue cycle', 'Managing clinical documentation improvement', 'Designs CDI programs with NLP-assisted query generation and documentation quality metrics. Use when implementing CDI programs, designing documentation queries, or measuring documentation quality.', 'Apply the "Managing clinical documentation improvement" skill. Designs CDI programs with NLP-assisted query generation and documentation quality metrics. Use when implementing CDI programs, designing documentation queries, or measuring documentation quality.'),
  ('managing-medical-staff-credentialing', 'bev', 'Credentialing', 'Managing medical staff credentialing', 'Structures credentialing verification with primary source documentation and privilege delineation. Use when processing credentials, verifying qualifications, or managing privilege requests.', 'Apply the "Managing medical staff credentialing" skill. Structures credentialing verification with primary source documentation and privilege delineation. Use when processing credentials, verifying qualifications, or managing privilege requests.'),
  ('managing-telehealth-compliance', 'bev', 'Compliance', 'Managing telehealth compliance', 'Evaluates telehealth program compliance with state licensing, prescribing, and reimbursement requirements. Use when assessing telehealth compliance, reviewing licensure requirements, or managing virtual care regulations.', 'Apply the "Managing telehealth compliance" skill. Evaluates telehealth program compliance with state licensing, prescribing, and reimbursement requirements. Use when assessing telehealth compliance, reviewing licensure requirements, or managing virtual care regulations.'),
  ('managing-substance-abuse-confidentiality', 'bev', 'Compliance', 'Managing substance abuse confidentiality', 'Applies 42 CFR Part 2 substance abuse confidentiality requirements with consent and disclosure protocols. Use when managing SUD records, applying Part 2 requirements, or handling substance abuse confidentiality.', 'Apply the "Managing substance abuse confidentiality" skill. Applies 42 CFR Part 2 substance abuse confidentiality requirements with consent and disclosure protocols. Use when managing SUD records, applying Part 2 requirements, or handling substance abuse confidentiality.'),
  ('auditing-hipaa-compliance', 'bev', 'Compliance', 'Auditing hipaa compliance', 'Conducts HIPAA compliance assessments with Privacy Rule, Security Rule, and Breach Notification analysis. Use when auditing HIPAA compliance, assessing privacy practices, or reviewing security controls.', 'Apply the "Auditing hipaa compliance" skill. Conducts HIPAA compliance assessments with Privacy Rule, Security Rule, and Breach Notification analysis. Use when auditing HIPAA compliance, assessing privacy practices, or reviewing security controls.')
ON CONFLICT (slug) DO UPDATE
  SET agent_id = EXCLUDED.agent_id,
      group_label = EXCLUDED.group_label,
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      prompt = EXCLUDED.prompt;
